// app/terms/page.tsx
import React from "react";

// export const metadata = {
//   title: "Webivus — Terms of Service",
//   description: "Terms of Service for Webivus",
// };

export default function TermsPage() {
  return (
    <div className="min-h-screen w-screen  text-white">
      <div className="w-screen  p-8  ">
        <header className="mb-6">
          <h1 className="text-2xl font-semibold">Webivus — Terms of Service</h1>
          <p className="mt-1 text-sm text-green-300">
            Effective Date: <span className="font-medium">22-09-2025</span> •
            Last Updated: <span className="font-medium">22-09-2025</span>
          </p>
        </header>

        <main className="prose prose-invert max-w-none text-sm leading-relaxed">
          <p>
            Welcome to Webivus. These Terms of Service (&quot;Terms&quot;)
            govern your access to and use of Webivus&apos; services, including
            our website, dashboard, plugins, APIs, and related features
            (collectively, the &quot;Services&quot;). By using Webivus, you
            agree to these Terms. If you do not agree, you may not use our
            Services.
          </p>

          <section aria-labelledby="eligibility" className="mt-6">
            <h2 id="eligibility" className="text-lg font-semibold">
              1. Eligibility
            </h2>
            <ul>
              <li>
                You must be at least 18 years old or the legal age of majority
                in your jurisdiction.
              </li>
              <li>
                By creating an account, you represent that all information you
                provide is accurate and complete.
              </li>
            </ul>
          </section>

          <section aria-labelledby="services-provided" className="mt-4">
            <h2 id="services-provided" className="text-lg font-semibold">
              2. Services Provided
            </h2>
            <p>
              Webivus provides AI-powered WordPress management tools, including
              but not limited to:
            </p>
            <ul>
              <li>
                Conversational AI agents for WordPress troubleshooting and
                assistance.
              </li>
              <li>Site performance insights and daily analysis.</li>
              <li>Rollback functionality for changes made by Webivus.</li>
              <li>Plugin connection for secure management.</li>
            </ul>
            <p>
              <strong>Note:</strong> Webivus does not provide site backups. It
              is the user’s sole responsibility to maintain up-to-date backups
              of their website.
            </p>
          </section>

          <section aria-labelledby="user-responsibilities" className="mt-4">
            <h2 id="user-responsibilities" className="text-lg font-semibold">
              3. User Responsibilities
            </h2>
            <p>You agree to:</p>
            <ul>
              <li>Use Webivus only for lawful purposes.</li>
              <li>Maintain the security of your login credentials.</li>
              <li>
                Ensure your WordPress site is properly backed up before using
                Webivus tools.
              </li>
              <li>
                Accept that Webivus may generate or edit code, but it is your
                responsibility to review changes before publishing.
              </li>
            </ul>
          </section>

          <section aria-labelledby="data-collection" className="mt-4">
            <h2 id="data-collection" className="text-lg font-semibold">
              4. Data Collection and Privacy
            </h2>
            <p>
              We collect: your site URL, chat history with Webivus, action logs,
              code generated by Webivus, email, and password.
            </p>
            <p>
              We do not collect your plugin code, theme code, or any unrelated
              sensitive website data.
            </p>
            <p>
              For more details, see our{" "}
              <a href="/landing/privacy" className="text-green-300 underline">
                Privacy Policy
              </a>
              .
            </p>
          </section>

          <section aria-labelledby="intellectual-property" className="mt-4">
            <h2 id="intellectual-property" className="text-lg font-semibold">
              5. Intellectual Property
            </h2>
            <ul>
              <li>
                Webivus retains ownership of all software, AI models, and
                content we provide.
              </li>
              <li>
                Users retain ownership of their websites, content, and data.
              </li>
              <li>
                By using Webivus, you grant us a limited license to process your
                site data for providing the Services.
              </li>
            </ul>
          </section>

          <section aria-labelledby="prohibited-uses" className="mt-4">
            <h2 id="prohibited-uses" className="text-lg font-semibold">
              6. Prohibited Uses
            </h2>
            <ul>
              <li>Attempt to hack, reverse engineer, or misuse Webivus.</li>
              <li>
                Use Webivus to distribute malware, spam, or unlawful content.
              </li>
              <li>Bypass authentication or security restrictions.</li>
              <li>
                Use Webivus for managing sites that violate applicable laws.
              </li>
            </ul>
          </section>

          <section aria-labelledby="disclaimer" className="mt-4">
            <h2 id="disclaimer" className="text-lg font-semibold">
              7. Disclaimer of Warranties
            </h2>
            <ul>
              <li>Webivus is provided “as is” and “as available”.</li>
              <li>
                We make no guarantees that Webivus will be error-free,
                uninterrupted, or compatible with all environments.
              </li>
              <li>
                Rollback does not guarantee full restoration of your site.
              </li>
            </ul>
          </section>

          <section aria-labelledby="limitation" className="mt-4">
            <h2 id="limitation" className="text-lg font-semibold">
              8. Limitation of Liability
            </h2>
            <p>To the maximum extent permitted by law:</p>
            <ul>
              <li>
                Webivus is not liable for lost profits, data loss, downtime, or
                damages arising from use of our Services.
              </li>
              <li>
                You are solely responsible for backing up your WordPress site
                and reviewing all changes.
              </li>
              <li>
                Our total liability for any claim will not exceed the amount you
                paid for the Services in the last 6 months.
              </li>
            </ul>
          </section>

          <section aria-labelledby="payments" className="mt-4">
            <h2 id="payments" className="text-lg font-semibold">
              9. Payments &amp; Subscriptions
            </h2>
            <ul>
              <li>Some Services require payment (monthly or yearly).</li>
              <li>
                By subscribing, you agree to recurring billing until canceled.
              </li>
              <li>Refunds are only provided as required by law.</li>
            </ul>
          </section>

          <section aria-labelledby="termination" className="mt-4">
            <h2 id="termination" className="text-lg font-semibold">
              10. Termination
            </h2>
            <ul>
              <li>
                We may suspend or terminate your account if you violate these
                Terms.
              </li>
              <li>
                You may stop using Webivus at any time by disabling the plugin
                and canceling your subscription.
              </li>
            </ul>
          </section>

          <section aria-labelledby="third-party" className="mt-4">
            <h2 id="third-party" className="text-lg font-semibold">
              11. Third-Party Services
            </h2>
            <p>
              Webivus may integrate with third-party services (e.g., Redis,
              MongoDB, analytics providers). We are not responsible for
              third-party providers’ actions or failures.
            </p>
          </section>

          <section aria-labelledby="indemnification" className="mt-4">
            <h2 id="indemnification" className="text-lg font-semibold">
              12. Indemnification
            </h2>
            <p>
              You agree to indemnify and hold harmless Webivus, its founders,
              employees, and affiliates from any claims, damages, or losses
              arising out of:
            </p>
            <ul>
              <li>Your use of the Services.</li>
              <li>
                Any changes Webivus makes to your site with your approval.
              </li>
              <li>Your violation of these Terms.</li>
            </ul>
          </section>

          <section aria-labelledby="modifications" className="mt-4">
            <h2 id="modifications" className="text-lg font-semibold">
              13. Modifications
            </h2>
            <p>
              We may update these Terms periodically. Updates will be posted on
              our website, and continued use means you accept the changes.
            </p>
          </section>

          <section aria-labelledby="governing-law" className="mt-4">
            <h2 id="governing-law" className="text-lg font-semibold">
              14. Governing Law
            </h2>
            <p>
              These Terms are governed by the laws of India (or Delaware, if
              incorporated in the U.S. later). Any disputes shall be resolved
              via binding arbitration in New Delhi, India, unless otherwise
              required by law.
            </p>
          </section>

          <section aria-labelledby="contact" className="mt-4">
            <h2 id="contact" className="text-lg font-semibold">
              15. Contact Us
            </h2>
            <p>
              For questions regarding these Terms: Email:{" "}
              <a
                href="mailto:hi@webivus.com"
                className="text-green-300 underline"
              >
                hi@webivus.com
              </a>
            </p>
          </section>
        </main>

        <div className="mt-8 text-sm text-gray-300">
          <p>
            Last updated: <span className="text-green-300">22-09-2025</span>
          </p>
        </div>
      </div>
    </div>
  );
}
