import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./app/components/Navbar";
import Header from "./app/components/Header";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Webivus",
  description: "Generated by willowave",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-[20px] mt-2 w-full flex gap-4 justify-center items-center mb-0.5">
          <Link href="/landing" className="text-[#626262] text-[12px]">
            intro
          </Link>
          <div className="w-[0.5px] h-full bg-[#626262]"></div>
          <Link href="/app" className="pb-2">
            Webivus
          </Link>
          <div className="w-[0.5px] h-full bg-[#626262]"></div>
          <div className="text-[#626262] text-[12px]">Beta</div>
        </div>
        <div className="h-[1px] bg-[radial-gradient(circle_at_center,_#959595,_#1e1e1e)]"></div>

        <div className="w-full">{children}</div>
      </body>
    </html>
  );
}
